### ISSUE TITLE
Random "ZZ_p: division by non-invertible element"

### ISSUE THREAD

**Issue by andreaTP** [vernamlab/cuHE#19]
It happens that an exception is thrown, probably during KeyGen of DHS, apparently randomly.

**Comment by WeiDaiWD** [comment]
Could you please trace back the error? I used to see the same exception, which hasn't occured for a long time.

**Comment by andreaTP** [comment]
ok, I will try to do something...

**Comment by andreaTP** [comment]
I track the error and it is thrown by NTL:
https://github.com/axelexic/NTL/blob/7cca5498abd2523c6b588b4de11af46a8c3fed29/src/gen_gmp_aux.c#L62

In this way even if it is a runtime exception your program will be aborted anyhow.

I'm going to propose a fix for this.

**Comment by WeiDaiWD** [comment]
I got this error when running Prince:
terminate called after throwing an instance of 'NTL::ArithmeticErrorObject'
what():  ZZ_pX: division by zero
Aborted (core dumped)

I guess there's a problem in keygen or DHS initialization. I'm looking into that.

**Comment by WeiDaiWD** [comment]
My problem is caused by batcher. I removed initialization of batching and it seems fine with Prince.
I'm thinking the batcher does not work with some parameters.
Let me know if your error is caused by batcher too.

**Comment by andreaTP** [comment]
Targeted with #22 .
Please review it.
