### ISSUE TITLE
A question about crt loop code

### ISSUE THREAD

**Issue by NanXiao** [vernamlab/cuHE#28]
Dear cuHE maintainers,

Greetings from me! I have a question about [crt](https://github.com/vernamlab/cuHE/blob/0f12349bc39550d8d8ad993e756875de37e22e36/cuhe/Base.cu#L857-L879) code:  

```
__global__ void crt(uint32 *dst, uint32 *src, int pnum, int w32, int mlen,
    int clen) {
	......
	for (int i=0; i<w32; i++)
		in[bdimx*i+tidx] = src[bidx*bdimx*w32+bdimx*i+tidx];
        __syncthreads();
        ......
}
```
I just wonder why we don't use the following one:   

```
__global__ void crt(uint32 *dst, uint32 *src, int pnum, int w32, int mlen,
    int clen) {
	......
	for (int i=0; i<w32; i++)
		in[tidx*w32+i] = src[idx*w32+i];
        ......
}
```
Since the above every for-loop can guarantee every thread can get a complete coefficient,  there is no need to synchronize the threads. Shouldn't it be more efficient? Thanks very much!

Best Regards
Nan Xiao

**Comment by WeiDaiWD** [comment]
Thanks for your attention. The upper one (in my code) ensures consecutive or coalesced global memory access (`src`) and likely bank-conflict free shared memory access (`in`). This is more efficient even though a `__syncthreads()` is forced. Hope this is sufficient for you question.

**Comment by NanXiao** [comment]
@WeiDaiWD Got it! Thanks for your comments!
