### ISSUE TITLE
cannot compile Base.cu

### ISSUE THREAD

**Issue by andreaTP** [vernamlab/cuHE#8]
I'm trying to check this awesome work!

Unfortunately now the problem is that I cannot compile Base.cu due to:
`Base.cu(253): error: calling a __device__ function("_add_modP") from a __host__ __device__ function("_ntt4") is not allowed`
and following.

I've checked and I can compile but not execute the dir developing in the ntt branch.

any hint?

**Comment by WeiDaiWD** [comment]
Sorry about that, I changed a little in ModP.h and forgot to submit Base.cu. It should work fine now.
Ps: Remember to change Makefile according to ur gpu's computation capability. Mine is 5.2, which can be found in Makefile by searching for "52".

Best regards,
Wei Dai
Worcester Polytechnic Institute

**Comment by andreaTP** [comment]
Great, thanx a lot!
I will play around this in the next days.

Super fast support!
