### ISSUE TITLE
double free or corruption in initCuHE

### ISSUE THREAD

**Issue by andreaTP** [vernamlab/cuHE#9]
Trying to run examples and tests fail on initCuHE with:
`double free or corruption (!prev):`

**Comment by WeiDaiWD** [comment]
I'll look into that this afternoon.

Best regards,
Wei Dai
Worcester Polytechnic Institute

**Comment by WeiDaiWD** [comment]
Was "double free or corruption" occurs in "AutoComplete"?
I'm currently having problem with the code, too.
I'm working on a new GPU and some tests show wrong results.
Please give me some time to fix it.
I'm deeply sorry.

On Wed, Feb 17, 2016 at 11:44 AM, Andrea Peruffo notifications@github.com
wrote:

> Trying to run examples and tests fail on initCuHE with:
> double free or corruption (!prev):
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/vernamlab/cuHE/issues/9>.

## 

Best regards,
Wei Dai
Worcester Polytechnic Institute

**Comment by WeiDaiWD** [comment]
Everything in the branch "master" works correctly now. I've just tested.
I'll looking into "examples/AutoComplete/" which is removed for now.
I'll add new cases to "tests". The previous ones seemed quite unnecessary and useless.
Please let me know if you find anything wrong, thx.

**Comment by andreaTP** [comment]
Thanks for the update unfortunately the example is still faulting:
`*** Error in `./simple_DHS': double free or corruption (!prev): 0x00000000025e2170 ***`

**Comment by andreaTP** [comment]
tests are working fine now!

**Comment by WeiDaiWD** [comment]
I'd love to help but I do not see that error.
Could you please isolate and locate the error in "/cuhe/CuHE.cu"?
